#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid

if [ "$1" == "start" ]
then
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
  kill "$(pgrep -f /manage_my_process)" 
  rm /var/run/my_process.pid
  echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
  kill "$(pgrep -f /manage_my_process)"
  rm /var/run/my_process.pid
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
